### PR TITLE
Simplify user test

### PR DESCRIPTION
**Pull request by jkozol**

### CODE REVIEW

**Comment by jkozol** [comment]
Removing testing is never ideal but I don't think these checks are important and I have opened issue #1336 to track reimplementing these checks in the future.

**Review by Gundersanne — CHANGES_REQUESTED** [review]
I think this is acceptable in this instance, but please create an issue and refer to it in a comment, stating why, or refer to the user creation rework issue.

**Comment by jkozol** [comment]
@Gundersanne Thanks for the review. I added a comment and linked to the issue.

**Review by Gundersanne — APPROVED** [review]
perfec, thanks!

**Comment by jkozol** [comment]
This 8-4 test failure is unrelated to the fix here. I will fix this failure in a separate PR.

**Pull request merged**
