### PR TITLE
Add new edge image type support and validation, reenable vmware

### PR DESCRIPTION
**Pull request by jkozol**
This reverts commit 08e46cdb3ef761f2f4d6d75c97e90d786ca86432. VMWare is now a selectable upload type.

### CODE REVIEW

**Review by teg — APPROVED** [review]
Thanks! cc @jmikovic

**Review by teg — APPROVED** [review]
🥳

**Review by larskarlitski — APPROVED** [review]
Very nice! Thanks for seeing this through!

**Comment by teg** [comment]
We are seeing some really bad CI flakes here apparently. They are not specific to this PR, and manual testing seems to work just fine. Considering the Firefox tests pass for both Fedora and RHEL, I vote in favor of merging as is, and doing having a discussion about the state of our CI next week to see how we can avoid a situation like this in the future.

**Pull request merged**
