### PR TITLE
Test fixes in preparation for f35/36 and RHEL 8.7/9.1

### PR DESCRIPTION
**Pull request by jkozol**

### CODE REVIEW

**Comment by martinpitt** [comment]
> Error: No inspectable targets

That got fixed in cockpit's testlib a while ago, please bump test/common checkout.

I don't have an idea about [that failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1449-20220720-121759-cbe7cdcf-rhel-8-6/log.html):
```
scp -B -r -p -P 2201 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o BatchMode=yes -o PKCS11Provider=none -o ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-87054 /work/bots/make-checkout-workdir/test/files root@[127.0.0.2]:/home/admin
scp: Couldn't canonicalize: No such file or directory
scp: Unable to canonicalize path "/home/admin/files"
scp: failed to upload directory /work/bots/make-checkout-workdir/test/files to /home/admin/files
```

**Comment by jkozol** [comment]
@yih-redhat Would you mind taking a look into why the f36 tests are failing?

**Comment by martinpitt** [comment]
@jkozol : I am looking at the [RHEL issue](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1449-20220720-130855-73f81506-rhel-8-6/log.html) in https://github.com/cockpit-project/bots/issues/3639 , that's related to our recent move to Fedora 36 as a test platform.

**Comment by jkozol** [comment]
@martinpitt Since we remove rhel-9-0 and rhel-8-6 in https://github.com/cockpit-project/bots/pull/3635 I think this is good to go. Any further thoughts?

**Review by martinpitt — APPROVED** [review]
Nice, thank you!

**Pull request merged**
