### PR TITLE
[rhel-8] Fix osbuild-composer start/stop issue

### PR DESCRIPTION
**Pull request by henrywang**

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
Thanks! Looks good to land once bots agree, and this should unblock PR #1220

**Comment by martinpitt** [comment]
[rhel-8-4](https://logs.cockpit-project.org/logs/pull-1221-20210125-055344-7647fc85-rhel-8-4/log.html) does not work yet as the test/common API is too old for the RHEL 8.4 cockpit version. It'd be best to bump it to the same version as master (233 right now)

**Comment by henrywang** [comment]
@martinpitt, there're really lots of dependences units to pick. Try to figure all of them out.

**Comment by henrywang** [comment]
We can close this PR because [rhel-8](https://github.com/osbuild/cockpit-composer/tree/rhel-8) branch has been reset to [tag 28](https://github.com/osbuild/cockpit-composer/releases/tag/28)

**Comment by martinpitt** [comment]
Thanks @henrywang ! Want to update https://github.com/cockpit-project/bots/blob/master/task/testmap.py#L131 or want me to?

**Pull request closed without merging**
