### PR TITLE
package.json: Lock @patternfly/react-styles version

### PR DESCRIPTION
**Pull request by martinpitt**
It's part of patternfly-react, so we should update it in a controlled
fashion. Letting it auto-update freely often breaks the build.

Similar to https://github.com/cockpit-project/cockpit/commit/bbde4c01947

### CODE REVIEW

**Comment by martinpitt** [comment]
This avoids [this kind of failures](https://logs.cockpit-project.org/logs/pull-1684-20210218-052956-38f52238-rhel-8-4-osbuild-cockpit-composer-rhel-8/log.html). That happened on the rhel8 branch (I'll send a backport in a moment), but could just as easily hit master. It recently did so for both cockpit and cockpit-podman, we did the same fix there.

**Comment by martinpitt** [comment]
Eh, what? That worked just fine locally...

**Comment by martinpitt** [comment]
Works now.

**Review by jkozol — APPROVED** [review]
This makes sense to me. Thanks.

**Pull request merged**
