### PR TITLE
test: switch to rhel-95, drop rhel-810

### PR DESCRIPTION
**Pull request by croissanne**
The rhel-9-4 and rhel-8-10 tests we should ignore, see https://github.com/cockpit-project/bots/pull/6716

### CODE REVIEW

**Comment by kingsleyzissou** [comment]
I mean it looks good to me, the tests failing is pretty weird though

**Comment by croissanne** [comment]
> I mean it looks good to me, the tests failing is pretty weird though
> 
> Edit: I see you're still debugging though

note that rhel 8-10 and 9-4 is expected to fail here, just fedora39/40, centos-9 and rhel-9-5 are meant to be green

**Comment by kingsleyzissou** [comment]
> note that rhel 8-10 and 9-4 is expected to fail here, just fedora39/40, centos-9 and rhel-9-5 are meant to be green

Thanks, I didn't realise that. But I guess I should have read the PR title properly

**Comment by kingsleyzissou** [comment]
If we're dropping `rhel-9-10` don't we want to remove it from the list of github actions too?

**Comment by croissanne** [comment]
> If we're dropping `rhel-8-10` don't we want to remove it from the list of github actions too?

That's determined by https://github.com/cockpit-project/bots/pull/6716, this gets green, we trigger the relevant tests on that PR, and rhel-8 and 94 won't be triggered anymore.

**Comment by kingsleyzissou** [comment]
> > If we're dropping `rhel-8-10` don't we want to remove it from the list of github actions too?
> 
> That's determined by [cockpit-project/bots#6716](https://github.com/cockpit-project/bots/pull/6716), this gets green, we trigger the relevant tests on that PR, and rhel-8 and 94 won't be triggered anymore.

Thanks for the clarification, I missed the linked PR. Clearly out of it this morning

**Comment by croissanne** [comment]
@kingsleyzissou  ok it's ready, was just a timeout on f39

**Review by kingsleyzissou — APPROVED** [review]
Thanks 🙏

**Pull request merged**
