### PR TITLE
Move to a webpack module, update cockpit test API to 290

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by martinpitt** [comment]
I pushed an initial set of updates. This still does not work, as webpack fails to try and resolve directory imports with an actual path that ends with `./index.js`. I'm running out of time (or insomnia), so this still needs work. We could fix all these imports, but this is stupid. This works in our other cockpit projects, so I figure there's some magic webpack option to turn this back on in module mode.

**Comment by martinpitt** [comment]
Hah, it was quite easy in the end, found it.

**Comment by martinpitt** [comment]
The remaining piece of work here is this:
```js
try {
  translations = require("../translations/compiled/" + userLocale + ".json");
} catch (error) {
  console.error(error);
  translations = require("../translations/compiled/en.json");
}
```
`require()` does not exist any more. Maybe this can be done using `await import().default`, but I'm not even sure if that would work as that's a JSON file, not a JS module. I think this rather needs to become `fetch()`. Unfortunately c-composer uses a completely different i18n system, so we can't use cockpit's.

**Comment by jelly** [comment]
A fetch won't work as the package does not ship the translations but bundles them:

```
[jelle@toolbox cockpit-composer]$ rpm -ql cockpit-composer
/usr/share/cockpit/composer
/usr/share/cockpit/composer/index.html
/usr/share/cockpit/composer/io.weldr.cockpit-composer.metainfo.xml
/usr/share/cockpit/composer/main.css
/usr/share/cockpit/composer/main.js
/usr/share/cockpit/composer/manifest.json
/usr/share/doc/cockpit-composer
/usr/share/doc/cockpit-composer/README.md
/usr/share/licenses/cockpit-composer
/usr/share/licenses/cockpit-composer/LICENSE.txt
/usr/share/metainfo/io.weldr.cockpit-composer.metainfo.xml
```

**Comment by martinpitt** [comment]
Unconflicted after landing #1885 , but I did not yet change the logic.

**Comment by martinpitt** [comment]
I updated the translation code, works for me now locally.

**Comment by martinpitt** [comment]
All fixed now, and I made double-sure that translations work (the integration tests don't check that). @jkozol can you please land this, so that we get a little closer to cockpit's current API? Thanks!

**Comment by martinpitt** [comment]
@jkozol : Does [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1884-20230612-165021-b82f9eed-rhel-9-2/log.html#3-2) ring a bell? Seems pretty stubborn.

**Comment by jkozol** [comment]
I am unsure what could be causing this error. Overall, the PR looks good to me.

@achilleas-k any thoughts what this error could be caused by?

```Jun 12 12:54:05 rhel-9-2-127-0-0-2-2201 osbuild-composer[11664]: 2023/06/12 12:54:05 DELETE /api/v0/blueprints/delete/testName
Jun 12 12:54:06 rhel-9-2-127-0-0-2-2201 osbuild-composer[19314]: No match for argument: testName
Jun 12 12:54:06 rhel-9-2-127-0-0-2-2201 osbuild-composer[19314]: error install_specs
Jun 12 12:54:06 rhel-9-2-127-0-0-2-2201 osbuild-composer[19314]: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
Jun 12 12:54:06 rhel-9-2-127-0-0-2-2201 osbuild-composer[19314]: missing packages: testName
Jun 12 12:54:06 rhel-9-2-127-0-0-2-2201 osbuild-composer[11664]: 2023/06/12 12:54:06 GET /api/v0/blueprints/info/testName
Jun 12 12:54:06 rhel-9-2-127-0-0-2-2201 osbuild-composer[11664]: 2023/06/12 12:54:06 GET /api/v0/blueprints/info/testName
```

As far as the UI shows this `testName` blueprint still exists.

**Comment by achilleas-k** [comment]
Is it the kernel option?  I just grepped through the source and saw
```
test/verify/check-blueprintWizard:34:        b.set_input_text("input[id='customizations.kernel.name']", "testName")
```

and composer treats a kernel name as a package name.

**Comment by martinpitt** [comment]
I get exactly the same failure in https://github.com/cockpit-project/bots/pull/4876 , so it seems that is not a regression from this PR.

**Comment by martinpitt** [comment]
Retry worked. @jkozol , can you review this one?

**Comment by martinpitt** [comment]
@jkozol friendly ping?

**Comment by jkozol** [comment]
@martinpitt Sorry. Was on PTO the last two weeks and not checking Github. Looks good to me and merging now

**Review by jkozol — APPROVED** [review]

**Comment by martinpitt** [comment]
No worries @jkozol , the urgent part landed before already. Thanks!

**Pull request merged**
