### PR TITLE
test: update rhel nightly baseurl

### PR DESCRIPTION
**Pull request by jkozol**
With the current development of rhel 8.4 the tests should use the rhel 8.4 nightlies. Also, the repos should be copied to both
/etc/osbuild-composer/rhel-8.json and rhel-8-beta.json.

### CODE REVIEW

**Comment by jkozol** [comment]
@henrywang Do you have any thoughts on why the fedora tests are failing? This PR shouldn't have any effect on them.

**Comment by henrywang** [comment]
> @henrywang Do you have any thoughts on why the fedora tests are failing? This PR shouldn't have any effect on them.

Working on that.

**Comment by mvollmer** [comment]
> > @henrywang Do you have any thoughts on why the fedora tests are failing? This PR shouldn't have any effect on them.
> 
> Working on that.

Oh, I ran into this as well.  This fixes it for me:

```
diff --git a/test/verify/composerlib.py b/test/verify/composerlib.py
index 09bafe38..f6ce4960 100644
--- a/test/verify/composerlib.py
+++ b/test/verify/composerlib.py
@@ -34,8 +34,9 @@ class ComposerCase(testlib.MachineCase):
         self.machine.write("/etc/cockpit/cockpit.conf", "[Session]\nIdleTimeout=0\n")
 
         # re-start osbuild-composer.socket
+        testlib.sit()
         self.machine.execute(script="""#!/bin/sh
-        systemctl stop --quiet osbuild-composer.socket && systemctl start osbuild-composer.socket
+        systemctl stop --quiet osbuild-composer.socket osbuild-composer.service && systemctl start osbuild-composer.socket
         """)
 
         # push pre-defined blueprint
```

Apparently systemd refuses to start the socket when the service is still running, which kinda makes sense. I have no idea what has changed that makes this fail now.

**Comment by henrywang** [comment]
Thanks @mvollmer! I think it's because of new systemd 247 release. The latest osbuild-composer released one week ago and no this kind of issue for last PR.

**Review by henrywang — APPROVED** [review]
Nice! Thanks @jkozol!

**Pull request merged**
