### PR TITLE
Makefile: don't run po-pull on dist

### PR DESCRIPTION
**Pull request by larskarlitski**
Updating translations and releasing a tarball are independent actions.

### CODE REVIEW

**Comment by martinpitt** [comment]
@bcl: This should take care of the cockpituous release failure.

**Comment by larskarlitski** [comment]
Test failure is unrelated to this Makefile change. Merging.

**Comment by bcl** [comment]
How do we include the latest translations if po-pull isn't going to be run on release? Is that something that cockpituous will do as a separate step?

**Comment by martinpitt** [comment]
In cockpit we have a bot that regularly (every week or so) creates PRs with the result of `make po-pull`. This sometimes causes test regressions because of invalid translations, so it really should be validated by CI (of course you need a test that actually checks a non-English language or two, but at *least* make sure that the build system can process the po files) and also (coarsely) by a human. Doing it automatically at release time is a lingering trap.

**Pull request merged**
