### PR TITLE
test: Use the @noretry decorator for check-image

### PR DESCRIPTION
**Pull request by Gundersanne**
This is blocked on https://github.com/cockpit-project/cockpit/pull/14680

### CODE REVIEW

**Comment by marusak** [comment]
Thanks @Gundersanne!
@henrywang is this the only place where you don't want the retry logic?

**Comment by Gundersanne** [comment]
Adding the blocked label again, release day is today so won't be blocked much longer, but it'll need to check out test/common from cockpit 229.

**Comment by henrywang** [comment]
> Thanks @Gundersanne!
> @henrywang is this the only place where you don't want the retry logic?

@marusak, sorry for late response. I'm just back from 8-day public holiday.
Yes. Only image building tests need skip retry.

**Comment by marusak** [comment]
@Gundersanne can you pick this back up and also checkout test/common 229? Thanks!

**Review by jkozol — APPROVED** [review]
Now that cockpit 229 is in stable this looks good to me

**Pull request merged**
