### PR TITLE
tests: Always check if elements are visible

### PR DESCRIPTION
**Pull request by marusak**
`wait_present` should be used just rarely as the meaning of this
function is "Wait until present in dom", while meaning of `wait_visible`
is "Wait until in dom and visible to user". Tests should really just
check what user sees. Using `wait_present` incorrectly can lead to
broken code (just now I was fixing accordion which would never open up,
but tests were happy as they were just checking with `wait_present`)

I haven't tried this, just `sed` it. Lets see what CI think :)

### CODE REVIEW

**Comment by marusak** [comment]
10 failing tests, seems that mostly on incorrect using of selects (not opening the select, just interacting with it). We have functions to do this properly in `test/common/testlib.py` so I'll take this as an opportunity to rewrite it into that :)

**Comment by marusak** [comment]
List of image types is fetched asynchronously. UI does not indicate this in any way, which is not great. But I think we can just simply check for it in tests.

**Comment by marusak** [comment]
oh, there is still one broken test, that needs fixing. Someone retried tests just now, so I don't have those runs available. So I'll wait until it finishes and then fix those remaining tests.

**Review by henrywang — APPROVED** [review]
Nice! Thanks @marusak!

**Pull request merged**
