### PR TITLE
Check for NPM dependency updates

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [ ] FAIL: npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update core-js done: https://github.com/cockpituous/welder-web/commits/npm-update-core-js-20200413-151818

**Comment by cockpituous** [comment]
Error accessing /repos/weldr/cockpit-composer/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://logs.cockpit-project.org/logs/npm-update-927-20200413-151717/

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "core-js-compat": "3.6.5",
```

**Comment by henrywang** [comment]
Close this PR due to duplicate with PR#943

**Pull request closed without merging**
